### ISSUE TITLE
windows build

### ISSUE THREAD

**Issue by joeblew99** [asticode/go-astilectron-demo#1]
this is working for me well.

I am on a Macbook, and was wondering how to build for windows ?
I think there is a docker that has the right wine stuff in it to allow buildng fro windows.
Otherwise i guess i just need to run windows in VirtualBox..

Let me know what you think.

**Comment by asticode** [comment]
@joeblew99 you have 2 solutions to build for windows, and you don't need a VM or docker for any of them:

- build your project only for windows/amd64 => when running the bundler add the `-w` flag.
- build your project for several environments => add an `environments` key to your bundler configuration:

```json
{
  "app_name": "Astilectron demo",
  "icon_path_darwin": "resources/gopher.icns",
  "icon_path_linux": "resources/gopher.png",
  "icon_path_windows": "resources/gopher.ico",
  "environments": [
    {"arch": "amd64", "os": "linux"},
    {"arch": "i386", "os": "windows"}
  ],
  "output_path": "output"
}
```

this way it will build your project for both linux/amd64 and windows/i386.

Does that answer your question?

**Comment by joeblew99** [comment]
@asticode thanks for quick reply.

All fixed now:

{
  "app_name": "Astilectron demo",
  "icon_path_darwin": "resources/gopher.icns",
  "icon_path_linux": "resources/gopher.png",
  "icon_path_windows": "resources/gopher.ico",
  "output_path": "output",
  "environments": [
    {"arch": "amd64", "os": "linux"},
    {"arch": "386", "os": "windows"}
  ]
}



Now to download a 4GB vagrant image for windows 10 to actually play with it.
