### ISSUE TITLE
Docs and/or software is wrong!

### ISSUE THREAD

**Issue by carlca** [asticode/go-astilectron-demo#11]
macOS 10.13.1
Go 1.9.2

I followed the steps entirely, including checking that $GOPATH/bin was in my $PATH. It failed when I tried to run `astilectron-bundler -v`. I received the error message:

zsh: command not found: astilectron-bundler

Presumably, an executable is not being built at some point. I could investigate but frankly, I am too tired. I had hoped for a little demo entertainment before closing in for the night but sadly 'twas not meant to be.

Any ideas? Thanks!

**Comment by carlca** [comment]
I saw the issue #9 about "failing on Darwin" but despite deleting the `bind.go` file in step 1, I still got the error. Over to you!

**Comment by asticode** [comment]
@carlca sorry to destroy your hope for a little demo entertainment :(

Maybe something got wrong during the `go get`.

What you can do is the following:

- `cd $GOPATH/src/github.com/asticode/go-astilectron-bundler`
- `make`

This should run `go install` on the bundler.

You can test it once again.

If it's still failing can you print what `ls -l $GOPATH/bin` outputs?

**Comment by carlca** [comment]
Don't worry Quentin, I just got some "first thing in the morning" entertainment instead! Seriously, that's a very cool piece of software! Before I look at it closely, I have to ask, in terms of effort, how much Golang is involved compared to other technologies?

**Comment by asticode** [comment]
In terms of effort, I'd say it's the same than when you develop a website: you spend the same amount of time server-side (your GO code) and the same amount of time front-side (your HTML/JS/CSS code) since all the complexity of creating windows, menus, adding icons, etc. is abstracted by astilectron.
