### ISSUE TITLE
FATA[0003] bundling failed: bundling for environment windows/386 failed: building failed: go: cannot find GOROOT directory: c:\go : exit status 2

### ISSUE THREAD

**Issue by di3663** [asticode/go-astilectron-demo#15]
FATA[0003] bundling failed: bundling for environment windows/386 failed: building failed: go: cannot find GOROOT directory: c:\go
: exit status 2

I do set GOROOT, and it's not c:\go

**Comment by asticode** [comment]
@di3663 can you paste here what you get when you execute `go env` ?

**Comment by di3663** [comment]
/d/TOOL/Z/Desktop # go env
set GOARCH=386
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=386
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\TOOL\Z\.gopath\
set GORACE=
set GOROOT=D:\TOOL\go
set GOTOOLDIR=D:\TOOL\go\pkg\tool\windows_386
set GCCGO=gccgo
set GO386=sse2
set CC=gcc
set GOGCCFLAGS=-m32 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\Z\AppData\Local\Temp\go-build720462579=/tmp/go-build -gno-record-gcc-switches
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config

**Comment by di3663** [comment]
I use go with msys2

**Comment by asticode** [comment]
@di3663 I've added the `GOROOT` environment variable in the bundler process, that may be the cause of your issue.

Can you `go get` the **bundler**, run `make` (or `go install ./astilectron-bundler` if it doesn't work), try again and let me know if that fixes your issue?

**Comment by di3663** [comment]
@asticode works now.
