### ISSUE TITLE
Add option to the bundler to execute uglifyjs on .js files

### ISSUE THREAD

**Issue by vegh1010** [asticode/go-astilectron-demo#16]
Is it possible to prevent other people from seeing the resources folder? All the code is visible to anyone that runs the exe file. If it's not possible then the next best thing would be use something like uglifyjs to compressor the files

**Comment by asticode** [comment]
@vegh1010 right now it's not possible to hide the content of the `resources` folder unfortunately. Using something like `uglifyjs` would be an option for the `.js` files but that wouldn't solve the problem for other types of files.

Alternatives are:
- see whether the [electron builder](https://github.com/electron-userland/electron-builder) can help us regarding that matter
- maybe split resources into 2 categories: `disembed` and `not disembed`. Then we could spawn a static files server in our GO that would serve the `not disembed` resources. That way some resources would not be created on disk, and would stay embedded in the binary. That wouldn't be 100% safe, but still safer than in clear on disk.

If you see other alternatives, I'm all ears, I do agree with you this may become a very important problem in the near future.

**Comment by vegh1010** [comment]
I see your point. I'm currently just working with js files so I guess compressing it would be my best choice. I'll be back if I find any alternative ways.

Merry Christmas to you :smile:

**Comment by asticode** [comment]
I've updated the title since after investigating a little bit further yesterday, I've come to the conlusion that it's not possible to protect the `resources` files and there will always exist a way to extract them in clear.

Therefore I think our best bet is to add an option to the bundler, so that it uses `uglifyjs` to make things harder for people to understand the content of the .js files.

Merry Christmas to you :)

**Comment by vegh1010** [comment]
Hi,

So I came across an issue where javascript library is undefined. I used gulp to write multiple js files (jquery, bootstrap and angular) into a file vendor.js so to avoid constant editing to index.html and I just had to include vendor.js. When I run the exe file, I get an error angular/jquery undefined but if I were to run index.html itself, there's no error. I had to include each js file path to index.html to resolve the error which isn't what I wanted.

Do you know what's causing the issue?

**Comment by asticode** [comment]
@vegh1010 my guess is that your `vendor.js` is trying to include libraries such as `jquery` through a relative path but when you execute the .exe, files are not there since you either didn't add them to your `resources` folder or they're not in the correct relative path.

Could you give me the 2 following information:
- how does your `vendor.js` import `jquery` exactly?
- what is your `resources` folder structure?

**Comment by vegh1010** [comment]
So I've written a gulp task that gets the list of js file from jsFiles. Writes it into vendor.js, uglify it and place it in './gulp/build/resources/app/js/'. So my index.html will be in the app folder and has <script src="js/vendor.js"></script>. I have written in other web application before and it works.

`var gulp = require('gulp');
var concat = require('gulp-concat');
var uglify = require('gulp-uglify');
var es = require('event-stream');

var jsFiles = [
    'bower_components/jquery/jquery.min.js',
    'bower_components/bootstrap/dist/js/bootstrap.js',
    'bower_components/angular/angular.js'
];

gulp.task('build-js', function() {
    console.log("Building vendor.js");
    var vendorBuild = gulp.src(jsFiles)
        .pipe(concat('vendor.js'))
        .pipe(uglify({"mangle": false}))
        .pipe(gulp.dest('./gulp/build/resources/app/js/'));

    return es.merge([vendorBuild])
});`

**Comment by asticode** [comment]
@vegh1010 is the `bower_components` folder in your `resources` folder?

**Comment by vegh1010** [comment]
No. All the js files has been merge into a single js file which is vendor.js, that file is in resources

**Comment by asticode** [comment]
OK got it. Do you get a 404 when `index.html` tries to load `js/vendor.js` when running the binary?

**Comment by vegh1010** [comment]
Nope. Just an error saying j query undefined in bootstrap

**Comment by asticode** [comment]
@vegh1010 I've added a way to execute custom commands to resources files such as `uglifyjs`. Check out [the doc](https://github.com/asticode/go-astilectron-bundler#adapt-resources) that should be self-explanatory.

I'll close this issue for now, but feel free to reopen it if you're experiencing any issues.
