### ISSUE TITLE
can't build in windows 10

### ISSUE THREAD

**Issue by jmesyan** [asticode/go-astilectron-demo#17]
when I execute the command   go get -u github.com/asticode/go-astilectron-demo/...
throw a error:
```
 package golang.org/x/crypto
crypto/ssh/terminal: directory "C:\\github\\src\\golang.org\\x\\crypto\\ssh\\terminal" is not using a known version control system
```

the environment ：
```
os: windows 10 enterprise edition 1709 , 64 bit
cpu: intel(R) Core(TM) m3-7y30 cpu @1.00GHZ  1.61GHZ
```

**Comment by asticode** [comment]
@jmesyan sometimes this message means your $GOPATH is kind of messed up. To make sure this is actually your problem, can you remove the whole `C:\\github\\src\\golang.org` directory, and try again running `go get`?

**Comment by jmesyan** [comment]
before the golang,org is  add by my self, if remove it, throw a error:
```
package golang.org/x/crypto/ssh/terminal: unrecognized import path "golang.org/x/crypto/ssh/terminal" (https fetch: Get https://golang.org/x/crypto/ssh/terminal?go-get=1: dial tcp 216.239.37.1:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.)
```

**Comment by asticode** [comment]
is your machine connected to internet?

**Comment by jmesyan** [comment]
I try to build in mac system, when execute the command:go get -u github.com/asticode/go-astilectron-demo/...
still get error:
```
cd /usr/local/project/src/golang.org; git submodule update --init --recursive
fatal: No url found for submodule path 'x/mobile' in .gitmodules
package golang.org/x/crypto/ssh/terminal: exit status 128
```

the environment:
```
MacBook Pro (Retina, 15-inch, Mid 2015)
cpu 2.5 GHz Intel Core i7
memory: 16 GB 1600 MHz DDR3
```

**Comment by jmesyan** [comment]
yes, my machine connnected to internet

**Comment by asticode** [comment]
@jmesyan seems like your GO installation has not been properly set up. Please visit [this page](https://golang.org/doc/install)

**Comment by asticode** [comment]
@jmesyan is your issue fixed?

**Comment by jmesyan** [comment]
ok, because use the -u paramter, it must get from the network, I get rid of it ,  then run ok, is that can build a app?

**Comment by asticode** [comment]
@jmesyan unfortunately I think Electron does not support mobile environments for now. Therefore as go-astilectron is based on Electron, you can't build the app in a mobile environment. Only in macosx, linux and windows.
