### ISSUE TITLE
Fatal error: runtime out of memory

### ISSUE THREAD

**Issue by mfswagner** [asticode/go-astilectron-demo#19]
/binary github.com/asticode/go-astilectron-demo
FATA[0088] bundling failed: bundling for environment linux/arm failed: building failed: # github.com/asticode/go-astilectron-demo

**Comment by asticode** [comment]
@mfswagner are you building the project on a device that doesn't have a lot of RAM (like a raspberry pi) ?

**Comment by mfswagner** [comment]
Yes it was a raspberry pi



Lane Wagner

Director of Software Engineering

Mobile: 435-632-0924

Office: 435-414-6162

Email: wagner@metal-fatigue-solutions.com



Metal Fatigue Solutions

St George Office

291 E 1400 S Ste 1

St. George, UT 84790

www.metal-fatigue-solutions.com<http://www.metal-fatigue-solutions.com/>

[1506359519054_image001.jpg]
St George Office     Los Angeles Office     Las Vegas Office     Prescott Office    New York Office
435-414-6162        424-228-4676            702-800-5542        435-414-6162      914-359-4724

________________________________

**Comment by asticode** [comment]
@mfswagner in that case, I would urge you to build the project on a machine that have more RAM and copy+execute the binary on your raspberry.

You can build your project for your raspberry using the `GOARCH` environment variable:

```GOARCH=arm go run ...```

You may have to use the `GOARM` variable as well: https://github.com/golang/go/wiki/GoArm.

Does that fix your issue?

**Comment by mfswagner** [comment]
I'm unsure, I actually ended up going a different route with the project. Thanks for the feedback though, it makes sense that that would fix it!



Lane Wagner

Director of Software Engineering

Mobile: 435-632-0924

Office: 435-414-6162

Email: wagner@metal-fatigue-solutions.com



Metal Fatigue Solutions

St George Office

291 E 1400 S Ste 1

St. George, UT 84790

www.metal-fatigue-solutions.com<http://www.metal-fatigue-solutions.com/>

[1506359519054_image001.jpg]
St George Office     Los Angeles Office     Las Vegas Office     Prescott Office    New York Office
435-414-6162        424-228-4676            702-800-5542        435-414-6162      914-359-4724

________________________________

**Comment by asticode** [comment]
Cheers
