### ISSUE TITLE
Run not bundled app and dev build

### ISSUE THREAD

**Issue by ryabenko-pro** [asticode/go-astilectron-demo#20]
Hi, thanks for your awesome project. 

I just want to check since I didn't found anything about it: if it even possible or planned to run app without need of bundling it and make a dev build with console available?

Thank you.

**Comment by asticode** [comment]
@ryabenko-pro first off thanks for your kind words :)

Regarding your question, it is possible to use **astilectron** without using the bootstrap and the bundler however I'd say it's more difficult. A good place to start would be the quick start of the **astilectron** project: https://github.com/asticode/go-astilectron#quick-start.

Does that answer your question?

**Comment by ryabenko-pro** [comment]
@asticode yes, it does! Thanks. 

One thing you should add there is `a.Wait()` call. I spent some time figuring out why example does not work )

**Comment by asticode** [comment]
You're right, just added it :)

Cheers
