### ISSUE TITLE
NO window is shown when I execute the demo

### ISSUE THREAD

**Issue by pgOrtiz90** [asticode/go-astilectron-demo#21]
I follow the steps indicated, and I do not receive any error after running "astilectron-bundler -v"

Then I execute the Astilectron demo.exe file generated in /output/windows-amd64 but any window appears.

I'm working on Windows 10

Any idea what can be happening?

**Comment by asticode** [comment]
@pgOrtiz90 could you execute the .exe with the `-v` flag and paste the output here?

**Comment by pgOrtiz90** [comment]
Do you mean Astilectron demo.exe -v? there is not output

And with after running astilectron-bundler -v

DEBU[0000] Resetting
DEBU[0000] Creating C:\Users\Pablo\AppData\Local\Temp\astibundler
DEBU[0000] Creating C:\Users\Pablo\go\src\github.com\asticode\go-astilectron-demo\output
DEBU[0000] Bundling for environment windows/amd64
DEBU[0000] Removing C:\Users\Pablo\go\src\github.com\asticode\go-astilectron-demo\output\windows-amd64
DEBU[0000] Creating C:\Users\Pablo\go\src\github.com\asticode\go-astilectron-demo\output\windows-amd64
DEBU[0000] Binding data
DEBU[0000] Removing C:\Users\Pablo\go\src\github.com\asticode\go-astilectron-demo\vendor_astilectron_bundler
DEBU[0000] Creating C:\Users\Pablo\go\src\github.com\asticode\go-astilectron-demo\vendor_astilectron_bundler
DEBU[0000] C:\Users\Pablo\AppData\Local\Temp\astibundler\astilectron-0.15.0.zip already exists, skipping download of https://github.com/asticode/astilectron/archive/v0.15.0.zip
DEBU[0000] Copying C:\Users\Pablo\AppData\Local\Temp\astibundler\astilectron-0.15.0.zip to C:\Users\Pablo\go\src\github.com\asticode\go-astilectron-demo\vendor_astilectron_bundler\astilectron.zip
DEBU[0000] C:\Users\Pablo\AppData\Local\Temp\astibundler\electron-windows-amd64-1.8.1.zip already exists, skipping download of https://github.com/electron/electron/releases/download/v1.8.1/electron-v1.8.1-win32-x64.zip
DEBU[0000] Copying C:\Users\Pablo\AppData\Local\Temp\astibundler\electron-windows-amd64-1.8.1.zip to C:\Users\Pablo\go\src\github.com\asticode\go-astilectron-demo\vendor_astilectron_bundler\electron.zip
DEBU[0000] Generating C:\Users\Pablo\go\src\github.com\asticode\go-astilectron-demo\bind_windows_amd64.go
DEBU[0001] Running rsrc for icon C:\Users\Pablo\go\src\github.com\asticode\go-astilectron-demo\resources\icon.ico into C:\Users\Pablo\go\src\github.com\asticode\go-astilectron-demo\windows.syso
DEBU[0001] Building for os windows and arch amd64
DEBU[0001] Executing go build -ldflags -s -X "main.AppName=Astilectron demo" -X "main.BuiltAt=2018-02-21 22:06:14.5216211 +0100 CET m=+1.254854601" -H windowsgui -o C:\Users\Pablo\go\src\github.com\asticode\go-astilectron-demo\output\windows-amd64\binary github.com\asticode\go-astilectron-demo
DEBU[0004] Moving C:\Users\Pablo\go\src\github.com\asticode\go-astilectron-demo\output\windows-amd64\binary to C:\Users\Pablo\go\src\github.com\asticode\go-astilectron-demo\output\windows-amd64\Astilectron demo.exe

Thanks for your quick response

**Comment by pgOrtiz90** [comment]
I changed the configuration at bundler.json And I set the name demo.exe  But the result it's the same. Not output. 

![captura](https://user-images.githubusercontent.com/7583624/36527962-d4e7c35c-17b3-11e8-9b2b-7b798549fc44.PNG)

I tried on a Lubuntu Virtual Machine and the same happens at first, no output. But after installing lib-conf-2-4 is working perfectly. 

I am still wil be interested on be able to running on my Windows machine

**Comment by asticode** [comment]
@pgOrtiz90 don't you have to set a specific permission to a file before being able to execute it? something like `chmod +x` on linux...

**Comment by pgOrtiz90** [comment]
As far as I know I don't have to. An demo.exe has already permission to execute (I checked it)

**Comment by wouterz** [comment]
On linux the file is created as non-executable. You need to use ```chmod +x``` as suggested before, to make the file executable. I have not yet tried a windows build.
