### ISSUE TITLE
On Windows a cmdline box is shown alogn the main window

### ISSUE THREAD

**Issue by marcelmiguel** [asticode/go-astilectron-demo#22]
Is it possible not to show the cmdline box when openning the app?
Is it possible to open the window on a secondary screen?

**Comment by asticode** [comment]
@marcelmiguel is this the same issue: https://github.com/asticode/go-astilectron/issues/18 ?

**Comment by marcelmiguel** [comment]
It can be. The problem is that the terminal box is shown as long as the GUI.
Executing "astilectron_bundler -v" shows go build is executed with "-H windowsgui", that looks correct, I'm trying other options of go build, but none of them work.

**Comment by asticode** [comment]
yeah the `windowsgui` ldflag usually do the trick. Which version of go and windows are you using?

**Comment by marcelmiguel** [comment]
W10 & Go 1.10

**Comment by deranjer** [comment]
Same exact setup here, same exact issue. go1.10 windows/amd64

**Comment by asticode** [comment]
Have you tested W10 + Go 1.9 to see whether this is an issue brought by Go 1.10?

**Comment by asticode** [comment]
Could you guys test on Go 1.10.1 ? I've tested it with Windows 10 and it's working properly.

**Comment by asticode** [comment]
hey guys, could you check out the last answer of [this issue](https://github.com/golang/go/issues/24232) and see if that helps in any way?

**Comment by asticode** [comment]
closing this issue as this is a duplicate of https://github.com/asticode/go-astilectron-bundler/issues/16
