### ISSUE TITLE
astihttp.Download failed in copy content

### ISSUE THREAD

**Issue by ZEROKISEKI** [asticode/go-astilectron-demo#23]
when I first to follow the guide to create the application, it's successful. However, after I clone the repo in another path and repeat the operation, it caused error:

```

  bundling failed: bundling for environment darwin/amd64 failed: binding data failed: provisioning 
  the vendor failed: provisioning electron vendor for OS darwin and arch amd64 failed: 
  downloading https://github.com/electron/electron/releases/download/v1.8.1/electron-v1.8.1-
  darwin-x64.zip into /var/folders/xk/ywxcpw651yqddj75zp7jkc480000gn/T/astibundler/electron-
  darwin-amd64-1.8.1.zip failed: astihttp.Download failed: astihttp: copying content from 
  https://github.com/electron/electron/releases/download/v1.8.1/electron-v1.8.1-darwin-x64.zip to 
  /var/folders/xk/ywxcpw651yqddj75zp7jkc480000gn/T/astibundler/electron-darwin-amd64-
  1.8.1.zip failed: read tcp 192.168.199.167:49806->54.231.114.98:443: read: operation timed out

```

Firstly I thought that maybe internet error caused  `read: operation timed out`, however when I try to get `https://github.com/electron/electron/releases/download/v1.8.1/electron-v1.8.1-darwin-x64.zip` in my chrome, it downloaded successfully(Because I live in China, I also use shadowsocks proxy to test, also failed).

Could you help me to solve the problem?

**Comment by asticode** [comment]
Mmmm this is weird... are you sure this is not a temporary error and if you try now it works?

**Comment by ZEROKISEKI** [comment]
yet it my school network problem(I try many times but failed, and I went to the company it well...), I decided to save the folder `vendor_astilectron_bundler` files `astilectron.zip` and `electron.zip`, when I create new project I copy the folder into the project and run `astilectron-bundler` well:joy::joy:
