### ISSUE TITLE
Problem while trying to download it

### ISSUE THREAD

**Issue by egroJ97** [asticode/go-astilectron-demo#26]
egroj97@SmallFootV:~$ go get -u github.com/asticode/go-astilectron-demo/...
\# cd /home/egroj97/go/src/golang.org/x/crypto; git pull --ff-only
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> master

package github.com/asticode/go-astilectron-demo
	imports golang.org/x/crypto/ssh/terminal: exit status 1
\# cd /home/egroj97/go/src/golang.org/x/sys; git pull --ff-only
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> master

package github.com/asticode/go-astilectron-demo
	imports golang.org/x/sys/unix: exit status 1

That is what happens when I try to install it, any ideas?

**Comment by asticode** [comment]
@egroJ97 mmm it seems other packages are failing to upgrade... Could you first try `go get` and then `go get -u`?

**Comment by egroJ97** [comment]
@asticode I get the following, it seems to be a problem with my go setup, I'm going to re-install it.

`egroj97@SmallFootV:~$ go get
can't load package: package .: no Go files in /home/egroj97
egroj97@SmallFootV:~$ cd go
egroj97@SmallFootV:~/go$ go get
can't load package: package .: no Go files in /home/egroj97/go
egroj97@SmallFootV:~/go$ go get -u
package _/home/egroj97/go: unrecognized import path "_/home/egroj97/go" (import path does not begin with hostname)
egroj97@SmallFootV:~/go$ 
`

**Comment by egroJ97** [comment]
Problem solved, just installed golang again and checked some of the environment variables again and now everything is stalling smoothly. Thank you very much.
