### ISSUE TITLE
Any way to open the developer console?

### ISSUE THREAD

**Issue by rcholic** [asticode/go-astilectron-demo#27]
I like this demo so far, and it offer pretty much what I need for a cross-platform app. I noticed that the right click is not supported and I don't find any way to open the developer console. Anyone knows?

**Comment by asticode** [comment]
@rcholic when using the bootstrap the shortcut "CTRL + d" will open the dev tools. Otherwise you can use https://github.com/asticode/go-astilectron/blob/master/window.go#L131 or https://github.com/asticode/go-astilectron/blob/master/window.go#L330.

Does that fix your issue?
