### ISSUE TITLE
CGO error

### ISSUE THREAD

**Issue by wouterz** [asticode/go-astilectron-demo#30]
Im trying to build for windows, linux and darwin, all amd64. Linux seems to work, both Win and Darwin give similar issues.

I am using cgo, which I have seen you comment on in another issue. But he never really answered if he did or did not use cgo. My project does use CGO, is this an issue?
```
DEBU[0003] Executing go build -ldflags -X "main.AppName=Validatie Module" -X "main.BuiltAt=2018-04-25 16:45:41.374744728 +0200 CEST m=+3.062722261" -s -o /home/wouter/go/src/lab.weave.nl/zin/astilectron-validation-module/output/darwin-amd64/binary lab.weave.nl/zin/astilectron-validation-module 
FATA[0012] bundling failed: bundling for environment darwin/amd64 failed: building failed: # lab.weave.nl/zin/xml-validation-module/vendor/github.com/lestrrat-go/libxml2/xsd
../xml-validation-module/vendor/github.com/lestrrat-go/libxml2/xsd/xsd.go:29:15: undefined: clib.XMLSchemaParse
../xml-validation-module/vendor/github.com/lestrrat-go/libxml2/xsd/xsd.go:40:15: undefined: clib.XMLSchemaParseFromFile
...
```

clib does contain CGO based functions, is CGO the issue?

**Comment by asticode** [comment]
@wouterz the first thing that comes to mind is you forgot to enable CGO. For that you need to use the [EnvironmentVariables attribute](https://github.com/asticode/go-astilectron-bundler/blob/master/bundler.go#L70). In your bundler configuration, add `"env": ["CGO_ENABLED": "1"]` to your environment configuration:
```json
{
  "environments": [
    {
      "os": "darwin",
      "arch": "amd64",
      "env": {"CGO_ENABLED": "1"}
    }
  ]
}
```

**Comment by wouterz** [comment]
Thanks for the speedy reply. Not fixed yet, another issue appeared (as CGO does).

current darwin error
```
FATA[0010] bundling failed: bundling for environment darwin/amd64 failed: building failed: # net
/usr/local/go/src/net/cgo_bsd.go:15:72: could not determine kind of name for C.AI_MASK
# os/user
/usr/local/go/src/os/user/getgrouplist_darwin.go: In function 'mygetgrouplist':
/usr/local/go/src/os/user/getgrouplist_darwin.go:14:11: warning: implicit declaration of function 'getgrouplist'; did you mean 'mygetgrouplist'? [-Wimplicit-function-declaration]
  int rv = getgrouplist(user, (int) group, buf, ngroups);
           ^~~~~~~~~~~~
           mygetgrouplist
: exit status 2 
```

currently the windows error is:
```
DEBU[0003] Executing go build -ldflags -s -X "main.AppName=Validatie Module" -X "main.BuiltAt=2018-04-25 17:53:52.70816294 +0200 CEST m=+3.355440399" -H windowsgui -o /home/wouter/go/src/lab.weave.nl/zin/astilectron-validation-module/output/windows-amd64/binary lab.weave.nl/zin/astilectron-validation-module 
FATA[0012] bundling failed: bundling for environment windows/amd64 failed: building failed: # runtime/cgo
gcc: error: unrecognized command line option '-mthreads'; did you mean '-pthread'?
```

For windows specifying a different gcc in the `env` should fix the issue I think. Any clues on the darwin build?

**Comment by asticode** [comment]
@wouterz it definitely seems like CGO errors. 

I agree with you regarding the second issue but I can't say about the first one.

If I were you, I would try to build your project manually without the bundler, come up with correct `go build` commands for each os and paste them here. I'll be able to see what's missing in the bundler.

Let me know.

**Comment by asticode** [comment]
@wouterz did you manage to fix your problem?

**Comment by wouterz** [comment]
@asticode Have been away for a while. Its likely that the issue will be fixed by using proper custom cross toolchains, but for the moment I just compile everything native on different systems.

As building the right toolchain seemed to be quite problematic and time consuming.

**Comment by asticode** [comment]
OK thanks for the update. Closing this issue.

Cheers
