### ISSUE TITLE
Can't run demo

### ISSUE THREAD

**Issue by arpitjindal97** [asticode/go-astilectron-demo#32]
```
[arpit:~/Desktop/workspace/go-astilectron-demo/output/linux-amd64 master]$ ./Astilectron\ demo
ERRO[0000] accept tcp 127.0.0.1:36327: use of closed network connection while TCP accepting
FATA[0000] running bootstrap failed: creating window failed: canceller.cancelled
[arpit:~/Desktop/workspace/go-astilectron-demo/output/linux-amd64 master]$
```

Demo in this repo doesn't match with <b>Quick Start</b> [here](https://github.com/asticode/go-astilectron#quick-start). Please provide some good doc on how to get started with updated code

**Comment by arpitjindal97** [comment]
libgconf was missing

**Comment by Xoristzatziki** [comment]
Same problem here. After installed all ok. Is libgconf crusial to the app? Seems that is no longer supported officially by ubuntu (so not installed by default).

Is a search for libdconf (in case libgconf is absent) difficult to implement?
(just started trying golang, so sorry for any inconvenience)

Thanks for the demo anyway.

**Comment by asticode** [comment]
@Xoristzatziki this lib was needed by Electron itself and my guess is that it was because we were still using a pretty old version of Electron.

However I've bumped the Electron version. Can you:

- make sure `libdconf` is **not** installed
- fetch the changes in `go-astilectron`
- run `go install github.com/asticode/go-astilectron-bundler/astilectron-bundler`
- try the demo again

and let me know whether you still need libdconf?

**Comment by Xoristzatziki** [comment]
Thanks for the answer. My problem was with lib**g**conf. Uninstalled libgconf, removed all asticode (_asticode directory in go/src/github.com/, binaries in go/bin and directory asticode in go/pkg/linux_amd64/github.com_). Followed again instructions and now `./Astilectron\ demo -v` runs without problems, but file `go-astilectron-bundler.a` in `go/pkg/linux_amd64/github.com/asticode` cannot be opened by file-roller.

**Comment by asticode** [comment]
Great! Glad the `4.0.1` version fixed that!

However I'm not sure what to think about the `go-astilectron-bundler.a` file not being openable by file-roller...
