### ISSUE TITLE
How to debug with vscode?

### ISSUE THREAD

**Issue by 107295472** [asticode/go-astilectron-demo#35]

**Comment by asticode** [comment]
The same way you debug any other GO app.

If you mean debugging the JS code, you can't with VSCODE. You need to use the [dev tools](https://github.com/asticode/go-astilectron#open-the-dev-tools).

Does that answer your question?

**Comment by 107295472** [comment]
The vendor path will not be configured

**Comment by 107295472** [comment]
C:\\Users\\Administrator\\AppData\\Roaming\\vendor\\astilectron-v0.24.0.zip\\astilectron-0.24.0 into C:\\Users\\Administrator\\AppData\\Roaming\\vendor\

**Comment by 107295472** [comment]
![20180713102135](https://user-images.githubusercontent.com/6436116/42669784-e7ac247a-8689-11e8-82b2-3c3fc7b90828.png)

**Comment by 107295472** [comment]
FATA[0006] bundling failed: bundling for environment windows/amd64 failed: building failed: # github.com/asticode/go-astilectron-demo
.\bind_windows_amd64.go:537:34: Asset redeclared in this block
        previous declaration at .\bind.go:3:34
.\bind_windows_amd64.go:623:39: AssetDir redeclared in this block
        previous declaration at .\bind.go:7:39
.\bind_windows_amd64.go:728:38: RestoreAssets redeclared in this block
        previous declaration at .\bind.go:11:38

**Comment by 107295472** [comment]
ResourcesPath: "index.html",
{"level":"fatal","msg":"running bootstrap failed: restoring resources failed: checking resources failed: getting checksum of assets failed: getting checksum of index.html failed: getting data from asset index.html failed: Asset index.html not found","time":"2018-07-13T14:59:14+08:00"}
