### ISSUE TITLE
Can I pop up a dialog with go？

### ISSUE THREAD

**Issue by weiyixuan** [asticode/go-astilectron-demo#38]
Is there any way to pop a modal dialog box with go code?

**Comment by asticode** [comment]
@weiyixuan right now there's not. 

You can pop a dialog box using JS though using `astilectron.showErrorBox` in your JS for instance (https://github.com/asticode/astilectron/blob/master/main.js#L464).

Does that fit your needs?

**Comment by weiyixuan** [comment]
yes, thanks!
