### ISSUE TITLE
bundling for environment windows/386 failed

### ISSUE THREAD

**Issue by itgeniusshuai** [asticode/go-astilectron-demo#39]
FATA[0100] bundling failed: bundling for environment windows/386 failed: building failed: ../../sirupsen/logrus/terminal_windows.go:10:2: cannot find package "github.com/konsorten/go-windows-terminal-sequences" in any of:
        /usr/local/Cellar/go/1.9.2/libexec/src/github.com/konsorten/go-windows-terminal-sequences (from $GOROOT)
        /Users/zhaoshuai/Documents/uxin_go_workspace/yxp-essearch-mysqlsync/src/github.com/konsorten/go-windows-terminal-sequences (from $GOPATH)
        /Users/zhaoshuai/go/src/github.com/konsorten/go-windows-terminal-sequences
../go-astilog/out.go:8:2: cannot find package "github.com/mattn/go-colorable" in any of:
        /usr/local/Cellar/go/1.9.2/libexec/src/github.com/mattn/go-colorable (from $GOROOT)
        /Users/zhaoshuai/Documents/uxin_go_workspace/yxp-essearch-mysqlsync/src/github.com/mattn/go-colorable (from $GOPATH)
        /Users/zhaoshuai/go/src/github.com/mattn/go-colorable

go env::
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/zhaoshuai/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.9.2/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.9.2/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/05/jj_5gfld4z5dp_q_8xmb73cw0000gn/T/go-build803324395=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

can it only build your os ?if I wan't to build a windows exe application,I must use a windows machine?

**Comment by asticode** [comment]
@itgeniusshuai my guess is you forgot to "go get" since the error is `../go-astilog/out.go:8:2: cannot find package "github.com/mattn/go-colorable"`.

Does it work when you `go get`?

**Comment by itgeniusshuai** [comment]
I do it you tell me and go get more unimport package ,then everything is ok,thank you,
