### ISSUE TITLE
How should I debug a project during its development?Does the command "astilectron-bundler -v" need to be used every time?

### ISSUE THREAD

**Issue by Beatrice950201** [asticode/go-astilectron-demo#47]
How to debug a project during the development process? Do you need to use the "astilectron-bundler -v" command every time? If this is the case, it may take me a lot of time. Is there any good solution?

**Comment by asticode** [comment]
Once you have executed `astilectron-bundler -v` for the first time (and if neither electron or astilectron versions change) you don't need to use the bundler to test things out.

All you need to do is `go run *.go -v` and that should be enough.

Let me know if that works.

**Comment by ndawg** [comment]
For me, changes in HTML files are only being rendered when the bundler is run. I'm using the bootstrapper with my BaseDirectoryPath set to `deps`. If I edit the files within `deps` that are generated, all I need to do is refresh the page. Editing from `resources` requires re-bundling.

**Comment by asticode** [comment]
@ndawg you're definitely right.

My next idea would be not to use the bundler for development purposes. Would that make sense?

**Comment by Beatrice950201** [comment]
> 一旦你`astilectron-bundler -v`第一次执行（如果电子或astilectron版本都没有改变）你就不需要使用捆绑器来测试了。
> 
> 你需要做的就是`go run *.go -v`这就足够了。
> 
> 如果有效，请告诉我。



> Once you have executed `astilectron-bundler -v` for the first time (and if neither electron or astilectron versions change) you don't need to use the bundler to test things out.
> 
> All you need to do is `go run *.go -v` and that should be enough.
> 
> Let me know if that works.



> Once you have executed `astilectron-bundler -v` for the first time (and if neither electron or astilectron versions change) you don't need to use the bundler to test things out.
> 
> All you need to do is `go run *.go -v` and that should be enough.
> 
> Let me know if that works.

Problem solved, thank you!

**Comment by Beatrice950201** [comment]
@asticode Problem solved! thank you
