### ISSUE TITLE
Unable to start the app on Linux

### ISSUE THREAD

**Issue by GarimaBathla** [asticode/go-astilectron-demo#48]
Hello,

I build the exe for Linux architecture but everytime I try to run it, it fails with below error:

Question: What are the dependencies for using go-astielectron?

1) Does it need a native GUI support? I am running this on linux machine which has no GUI support.

DEBU[0000] Starting cmd /tmp/vendor/electron-linux-amd64/electron /tmp/vendor/astilectron/main.js 127.0.0.1:34689 false  app_name= source="executer.go:17"
DEBU[0000] Stderr says: /tmp/vendor/electron-linux-amd64/electron: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory  app_name= source="astilectron.go:290"

**Comment by asticode** [comment]
My guess is that Electron needs minimal dependencies set up on the machine. Check out [the doc](https://electronjs.org/docs/development/build-instructions-linux).

Does that answer your question?

**Comment by GarimaBathla** [comment]
Hi asticode:

So there might be dependencies. I am not able to install those dependencies. I was hoping with X11 protocol forwarding this should work. but it really doesn't. When I try to run with X11 forwarding on I get ```- -bash: ELF: command not found```

Would you know if I want to render a GUI on headless SUSE linux, with X11 how to go about it?

Please note I don't have liberty to do new system installation (I guess in this case it is really looking for chrome developer tools) that library (libnss3.so) is used by chrome developer tools.

**Comment by asticode** [comment]
Mmm I can't really help you on that, sorry. Your best bet would be checking out [Electron's issues](https://github.com/electron/electron/issues) directly I guess.
