### ISSUE TITLE
.exe can't run，and my os is win10 64

### ISSUE THREAD

**Issue by mr-chen-king** [asticode/go-astilectron-demo#50]
>  this is logs

- DEBU[0000] Creating D:\works\gowork\src\github.com\asticode\go-astilectron-demo\output  source="bundler.go:316"
- DEBU[0000] Bundling for environment windows/amd64        source="bundler.go:324"
- DEBU[0000] Binding data                                  source="bundler.go:336"
- DEBU[0000] Removing C:\Users\mrchen\AppData\Local\Temp\astibundler\bind  - -source="bundler.go:415"
- DEBU[0000] Creating C:\Users\mrchen\AppData\Local\Temp\astibundler\bind  source="bundler.go:422"
- DEBU[0000] Creating C:\Users\mrchen\AppData\Local\Temp\astibundler\bind\vendor_astilectron_bundler  source="bundler.go:467"
- DEBU[0000] Creating C:\Users\mrchen\AppData\Local\Temp\astibundler\cache  source="bundler.go:474"
- DEBU[0000] C:\Users\mrchen\AppData\Local\Temp\astibundler\cache\astilectron-0.33.0.zip already exists, skipping download of https://github.com/asticode/astilectron/archive/v0.33.0.zip  source="bundler.go:503"
- DEBU[0000] Copying C:\Users\mrchen\AppData\Local\Temp\astibundler\cache\astilectron-0.33.0.zip to C:\Users\mrchen\AppData\Local\Temp\astibundler\bind\vendor_astilectron_bundler\astilectron.zip  source="bundler.go:512"
- DEBU[0000] C:\Users\mrchen\AppData\Local\Temp\astibundler\cache\electron-windows-amd64-4.0.1.zip already exists, skipping download of https://github.com/electron/electron/releases/download/v4.0.1/electron-v4.0.1-win32-x64.zip  sourc
e="bundler.go:503"
- DEBU[0000] Copying C:\Users\mrchen\AppData\Local\Temp\astibundler\cache\electron-windows-amd64-4.0.1.zip to C:\Users\mrchen\AppData\Local\Temp\astibundler\bind\vendor_astilectron_bundler\electron.zip  source="bundler.go:512"
- DEBU[0000] Creating C:\Users\mrchen\AppData\Local\Temp\astibundler\bind\resources  source="bundler.go:552"
- DEBU[0000] Copying D:\works\gowork\src\github.com\asticode\go-astilectron-demo\resources to C:\Users\mrchen\AppData\Local\Temp\astibundler\bind\resources  source="bundler.go:560"
- DEBU[0000] Generating D:\works\gowork\src\github.com\asticode\go-astilectron-demo\bind_windows_amd64.go  source="bundler.go:459"
- DEBU[0003] Running rsrc for icon D:\works\gowork\src\github.com\asticode\go-astilectron-demo\resources\icon.ico into D:\works\gowork\src\github.com\asticode\go-astilectron-demo\windows.syso  source="bundler.go:595"
- DEBU[0003] Removing D:\works\gowork\src\github.com\asticode\go-astilectron-demo\output\windows-amd64  source="bundler.go:415"
- DEBU[0003] Creating D:\works\gowork\src\github.com\asticode\go-astilectron-demo\output\windows-amd64  source="bundler.go:422"
- DEBU[0003] Building for os windows and arch amd64        source="bundler.go:375"
- DEBU[0003] Executing go build -ldflags -H "windowsgui" -X "main.AppName=Astilectron demo" -X "main.BuiltAt=2019-10-27 12:49:22.2313236 +0800 CST m=+3.882993401" -o - -D:\works\gowork\src\github.com\asticode\go-astilectron-demo\output\w
indows-amd64\binary github.com\asticode\go-astilectron-demo  source="bundler.go:393"
- DEBU[0014] Moving D:\works\gowork\src\github.com\asticode\go-astilectron-demo\output\windows-amd64\binary to D:\works\gowork\src\github.com\asticode\go-astilectron-demo\output\windows-amd64\Astilectron demo.exe  source="bundler.go:7
41"

**Comment by asticode** [comment]
Can you run the `.exe` file with the `-v` flag (`astilectron-demo -v`) and paste logs here ?

**Comment by mr-chen-king** [comment]
Thanks , i will have a try when i come back home
