### ISSUE TITLE
can't run the demo with go.mod

### ISSUE THREAD

**Issue by bdarge** [asticode/go-astilectron-demo#55]
I cloned the demo. 
I did `go mod tidy`
the, `astilectron-bundler -v` result in:

```
FATA[0012] bundling failed: bundling for environment darwin/amd64 failed: building failed: # github.com/asticode/go-astilectron-demo
./bind_darwin_amd64.go:537:6: Asset redeclared in this block
        previous declaration at ./bind.go:3:34
./bind_darwin_amd64.go:623:6: AssetDir redeclared in this block
        previous declaration at ./bind.go:7:39
./bind_darwin_amd64.go:728:6: RestoreAssets redeclared in this block
        previous declaration at ./bind.go:11:38
: exit status 2  source="source_hook.go:17"
```

Can you please advice the cause of this problem?

**Comment by asticode** [comment]
Did you follow the whole [first step](https://github.com/asticode/go-astilectron-demo#step-1-install-the-demo) of installation?

Specifically did you run `rm $GOPATH/src/github.com/asticode/go-astilectron-demo/bind.go`?

Does that fix your problem?

**Comment by bdarge** [comment]
Yes, it did. I overlooked that. thanks.

 If we need to remove it, can it be added in `.gitignore`

**Comment by asticode** [comment]
Unfortunately we can't remove it from the project since it needs to be present so that `go get` works 😞
