### ISSUE TITLE
about packaging 

### ISSUE THREAD

**Issue by akzhou** [asticode/go-astilectron-demo#59]
hi @asticode,when I packaging an app using astilectron-bundler,and the bootstrap code in main.go function,it works!
but didn't when the code move to anthor directory like this,how to do it ?
```
func setupReleaseMode() (err error)  {

	logrus.Info("hhaha")

	// Run bootstrap
	if err := bootstrap.Run(bootstrap.Options{
		Asset:    Asset,
		AssetDir: AssetDir,
		AstilectronOptions: astilectron.Options{
			AppName:            "Hello World",
			SingleInstance:     true,
			VersionAstilectron: "0.34.0",
			VersionElectron:    "4.0.1",
		},
		Debug:  true,
		Logger: astilog.GetLogger(),
		OnWait: func(_ *astilectron.Astilectron, ws []*astilectron.Window, _ *astilectron.Menu, _ *astilectron.Tray, _ *astilectron.Menu) error {
			logrus.Info("onwait.....")
			return nil
		},
		RestoreAssets: RestoreAssets,
		Windows: []*bootstrap.Window{{
			Homepage:       "index.html",
			MessageHandler: nil,
			Options: &astilectron.WindowOptions{
				BackgroundColor: astikit.StrPtr("#333"),
				Center:          astikit.BoolPtr(true),
				Height:          astikit.IntPtr(700),
				Width:           astikit.IntPtr(700),
			},
		}},
	}); err != nil {
		logrus.Info("running bootstrap failed:",err)
		astilog.Fatal(errors.Wrap(err, "running bootstrap failed"))
	}

	return
}

//log
running bootstrap failed:restoring resources failed: restoring resources failed: creating /private/var/folders/vn/95bglsw56090qxr46k6r_qvw0000gn/T/resources/checksums.json
```

**Comment by asticode** [comment]
It seems the error message is truncated and is missing the last part which is important.

Could you paste here the entire error message ?

**Comment by akzhou** [comment]
> It seems the error message is truncated and is missing the last part which is important.
> 
> Could you paste here the entire error message ?

@asticode  : )

```
time="2020-02-28T17:51:58+08:00" level=info msg="running bootstrap failed:restoring resources failed: restoring resources failed: creating /var/folders/vn/95bglsw56090qxr46k6r_qvw0000gn/T/go-build284483824/b001/exe/resources/checksums.json failed: open /var/folders/vn/95bglsw56090qxr46k6r_qvw0000gn/T/go-build284483824/b001/exe/resources/checksums.json: no such file or directory" 
```

I print the path "/var/folders/vn/95bglsw56090qxr46k6r_qvw0000gn/T/go-build284483824/b001/exe: no such file or directory"

**Comment by akzhou** [comment]
> > It seems the error message is truncated and is missing the last part which is important.
> > Could you paste here the entire error message ?
> 
> @asticode : )
> 
> ```
> time="2020-02-28T17:51:58+08:00" level=info msg="running bootstrap failed:restoring resources failed: restoring resources failed: creating /var/folders/vn/95bglsw56090qxr46k6r_qvw0000gn/T/go-build284483824/b001/exe/resources/checksums.json failed: open /var/folders/vn/95bglsw56090qxr46k6r_qvw0000gn/T/go-build284483824/b001/exe/resources/checksums.json: no such file or directory" 
> ```
> 
> I print the path "/var/folders/vn/95bglsw56090qxr46k6r_qvw0000gn/T/go-build284483824/b001/exe: no such file or directory"

oh,I found the solution, "bind" key need set to bundler.json, indicate the path for generate  bind_xxx.go. thank you !

**Comment by asticode** [comment]
cheers

**Comment by MikeGrateful** [comment]
> > > It seems the error message is truncated and is missing the last part which is important.
> > > Could you paste here the entire error message ?
> > 
> > 
> > @asticode : )
> > ```
> > time="2020-02-28T17:51:58+08:00" level=info msg="running bootstrap failed:restoring resources failed: restoring resources failed: creating /var/folders/vn/95bglsw56090qxr46k6r_qvw0000gn/T/go-build284483824/b001/exe/resources/checksums.json failed: open /var/folders/vn/95bglsw56090qxr46k6r_qvw0000gn/T/go-build284483824/b001/exe/resources/checksums.json: no such file or directory" 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I print the path "/var/folders/vn/95bglsw56090qxr46k6r_qvw0000gn/T/go-build284483824/b001/exe: no such file or directory"
> 
> oh,I found the solution, "bind" key need set to bundler.json, indicate the path for generate bind_xxx.go. thank you !

bros How did you solve it
