### ISSUE TITLE
The output app can not run 

### ISSUE THREAD

**Issue by thomas-ye** [asticode/go-astilectron-demo#60]
I have use "chmod 4755" and "chown root ", but  it still can not run.

thomas@dev-desktop:~/go/src/github.com/asticode/go-astilectron-demo$ output/linux-amd64/Astilectron\ demo

2020/05/04 01:40:34 Running app built at 2020-05-04 01:32:47.821382388 +0800 CST m=+2.831355205
2020/05/04 01:40:34 astikit: starting worker...
2020/05/04 01:40:34 astikit: received signal urgent I/O condition
2020/05/04 01:40:34 astikit: received signal urgent I/O condition
2020/05/04 01:40:34 astikit: received signal urgent I/O condition
2020/05/04 01:40:34 astikit: received signal urgent I/O condition
2020/05/04 01:40:34 astikit: received signal urgent I/O condition
2020/05/04 01:40:34 Skipping restoring resources...
2020/05/04 01:40:34 Starting...
2020/05/04 01:40:34 Provisioning...
2020/05/04 01:40:34 Astilectron has already been provisioned to version 0.38.0, moving on...
2020/05/04 01:40:34 Electron has already been provisioned to version 7.1.10, moving on...
2020/05/04 01:40:34 Listening...
2020/05/04 01:40:34 Executing...
2020/05/04 01:40:34 Starting cmd /home/thomas/go/src/github.com/asticode/go-astilectron-demo/output/linux-amd64/vendor/electron-linux-amd64/electron /home/thomas/go/src/github.com/asticode/go-astilectron-demo/output/linux-amd64/vendor/astilectron/main.js 127.0.0.1:46109 true
2020/05/04 01:40:34 Stderr says: [25094:0504/014034.954566:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /home/thomas/go/src/github.com/asticode/go-astilectron-demo/output/linux-amd64/vendor/electron-linux-amd64/chrome-sandbox is owned by root and has mode 4755.
2020/05/04 01:40:34 '/home/thomas/go/src/github.com/asticode/go-astilectron-demo/output/linux-amd64/vendor/electron-linux-amd64/electron' exited with code: -1
2020/05/04 01:40:34 App has crashed
2020/05/04 01:40:34 Stopping...
2020/05/04 01:40:34 astikit: stopping worker...
2020/05/04 01:40:34 astikit: received signal child exited
2020/05/04 01:40:34 Closing...
2020/05/04 01:40:34 accept tcp 127.0.0.1:46109: use of closed network connection while TCP accepting
2020/05/04 01:40:34 Stopping...
2020/05/04 01:40:34 running bootstrap failed: creating window failed: context canceled

**Comment by asticode** [comment]
Per https://github.com/electron/electron/issues/17972, can you add a `ElectronSwitches` option to `AstilectronOptions` in `boostrap.Run` and set its value to `[]string{"--no-sandbox"}`? This should disable sandboxing which seems to be failing on your system.
