### ISSUE TITLE
fail to build switching from 32 bit to 64bit 

### ISSUE THREAD

**Issue by ajeecai** [asticode/go-astilectron-demo#61]
Hi, 

Get this demo and following the instruction with bundler.json to have this:
```
-  "icon_path_windows": "resources/icon.ico"
+  "icon_path_windows": "resources/icon.ico",
+       "environments": [
+       {"arch": "amd64", "os": "linux"},
+       {"arch": "386", "os": "windows"}
+       ]
 }
```
Building is OK with two outputs.

Then switch it to from {"arch": "386", "os": "windows"} to {"arch": "amd64", "os": "windows"} , never get it passed, the error is:

> /usr/bin/ld: i386 architecture of input file `/tmp/go-link-876960528/000000.o' is incompatible with i386:x86-64 output

` rm /tmp/astibundler/cache/ -rf ` is not helpful.

Thanks

**Comment by asticode** [comment]
@ajeecai check out [this issue](https://github.com/asticode/go-astilectron-demo/issues/28)

**Comment by ajeecai** [comment]
Hi @asticode , I check the issue you mentioned, where I am in the discussion too :) 

But it doesn't help, since in my project I have this "ldflags":{"linkmode":["internal"]} in bundler.json but seems this error, so I tried with this  go-astilectron-demo, also get the same. BTW, without support of '-v', I don't know how to get the full debug log now.

**Comment by asticode** [comment]
Mmmm I don't really know where your error is coming from and unfortunately I can't reproduce it 😞  However regarding logs, you should get full debug logs in stdout/stderr without the need of the `-v` flag.
