### ISSUE TITLE
How to change title url notification? (windows)

### ISSUE THREAD

**Issue by jakebrand24** [asticode/go-astilectron-demo#63]
![image](https://user-images.githubusercontent.com/61855831/86520206-18339300-be6c-11ea-92dc-3ae9926767b7.png)

**Comment by jakebrand24** [comment]
![image](https://user-images.githubusercontent.com/61855831/86520233-4f09a900-be6c-11ea-82e5-0560793b13a1.png)
This is full example!

**Comment by asticode** [comment]
Which OS are you testing on ?

**Comment by jakebrand24** [comment]
> Which OS are you testing on ?

im using windows 10

**Comment by asticode** [comment]
My guess is that the app needs to be signed but I'm really not sure about it. It seems people are experiencing the same issue when using Electron without building it, but I couldn't find out why.

**Comment by jakebrand24** [comment]
tks you
