### ISSUE TITLE
Why can't use external js

### ISSUE THREAD

**Issue by PittYao** [asticode/go-astilectron-demo#65]
## code framework
![image](https://user-images.githubusercontent.com/26101917/100302386-304fae80-2fd5-11eb-98d7-7adcb7621b9f.png)

## code

1. index.html include jquery
![image](https://user-images.githubusercontent.com/26101917/100302016-5fb1eb80-2fd4-11eb-85fd-1dc4ef44debf.png)

2. index.js use jquery
![image](https://user-images.githubusercontent.com/26101917/100302227-cfc07180-2fd4-11eb-9654-910c9cc4aec2.png)

3. make exe but console Uncaught ReferenceError: $ is not defined 
![image](https://user-images.githubusercontent.com/26101917/100301945-3beea580-2fd4-11eb-9e3d-bf072fb97da6.png)

##

**Comment by asticode** [comment]
Maybe this can help:

- https://github.com/asticode/go-astilectron/issues/256
- https://github.com/asticode/go-astilectron/issues/244#issuecomment-626167003
- https://github.com/asticode/go-astilectron/issues/26#issuecomment-315599257

**Comment by PittYao** [comment]
thanks. The third one can help me.

**Comment by PittYao** [comment]
> Maybe this can help:
> 
> * [asticode/go-astilectron#256](https://github.com/asticode/go-astilectron/issues/256)
> * [asticode/go-astilectron#244 (comment)](https://github.com/asticode/go-astilectron/issues/244#issuecomment-626167003)
> * [asticode/go-astilectron#26 (comment)](https://github.com/asticode/go-astilectron/issues/26#issuecomment-315599257)

thanks. The third one can help me.
