### ISSUE TITLE
Cannot bundle the demo example

### ISSUE THREAD

**Issue by true-zero** [asticode/go-astilectron-demo#66]
I'm attempting to bundle this demo repository before I bundle my project, however I'm running into issues: 

    2021/04/19 13:35:26 bundling failed: bundling for environment windows/amd64 failed: building failed: can't load package: package go-astilectron-demo is not in GOROOT (C:\Go\src\go-astilectron-demo)

**Comment by AlstonLicoder** [comment]
I have the same problem. My project is not at the GOROOT, so it couldn't complie. I want to know how can I change the path without using "astilectron-bundler" to make the ".exe" in win10.
