### ISSUE TITLE
astilectron-bundler: command not found

### ISSUE THREAD

**Issue by khigor777** [asticode/go-astilectron-demo#7]
I have tryed run astilectron-bundler, but got error on step 3.
astilectron-bundler: command not found
$ cd $GOPATH/src/github.com/asticode/go-astilectron-demo
$ astilectron-bundler -v
My OS: Linux LM 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Any help?

**Comment by asticode** [comment]
Is `$GOPATH/bin` in your `$PATH` ? Can you check there's a `astilectron-bundler` in `$GOPATH/bin`?

**Comment by khigor777** [comment]
Thank's a lot. It's fix my problem.
