### ISSUE TITLE
Bundler Issue

### ISSUE THREAD

**Issue by linclt** [asticode/go-astilectron-demo#73]
when i use astilectron-bundler, i change the bundler.json like this:
{
    "app_name": "Astilectron demo1",
    "icon_path_darwin": "resources/icon.icns",
    "icon_path_linux": "resources/icon.png",
    "icon_path_windows": "resources/icon.ico"
}
,i get this error:
![image](https://user-images.githubusercontent.com/46485507/140446441-06743180-db79-459f-87ae-c5f8f32e591c.png)

**Comment by linclt** [comment]
Sometimes update the index and static in the resource/app folder, the exe file generated after astilectron-bundler still uses the previous index and static

**Comment by linclt** [comment]
I have change the index.html and static, but after bundler, the application still gives me the former page

**Comment by asticode** [comment]
Can you share your code where you call `bootstrap.Run` ?

**Comment by linclt** [comment]
> Can you share your code where you call `bootstrap.Run` ?

![image](https://user-images.githubusercontent.com/46485507/140478568-7d7b224b-f21a-43d4-be41-e0d15ff4e93a.png)

I just use the demo

**Comment by asticode** [comment]
Can you share the content of your `resources/app` folder ?

**Comment by linclt** [comment]
> Can you share the content of your `resources/app` folder ?

sure
![image](https://user-images.githubusercontent.com/46485507/140487740-c78afe20-406f-4598-ad74-4d76070ae35a.png)
index.html:
<!DOCTYPE html><html><head><meta charset=utf-8><meta name=viewport content="width=device-width,initial-scale=1"><title>demo</title><link href=./static/css/app.30790115300ab27614ce176899523b62.css rel=stylesheet></head><body><div id=app></div><script type=text/javascript src=./static/js/manifest.3ad1d5771e9b13dbdad2.js></script><script type=text/javascript src=./static/js/vendor.8aa87dd3c903ad781810.js></script><script type=text/javascript src=./static/js/app.b22ce679862c47a75225.js></script></body></html>
![image](https://user-images.githubusercontent.com/46485507/140488017-30466fe8-a88e-4326-b0e3-8e4dd68d68ee.png)

it`s a vue example

**Comment by asticode** [comment]
Can you tell me whether the `index.html` file is present in `C:/Users/Administrator/AppData/Roaming/Astilectron Demo1/resources/app` ?

**Comment by linclt** [comment]
> Can you tell me whether the `index.html` file is present in `C:/Users/Administrator/AppData/Roaming/Astilectron Demo1/resources/app` ?

no

**Comment by linclt** [comment]
> > Can you tell me whether the `index.html` file is present in `C:/Users/Administrator/AppData/Roaming/Astilectron Demo1/resources/app` ?
> 
> it is not present in that file

just have vendor, and don`t have  resources

**Comment by asticode** [comment]
Can you share the file/folder structure in your go project ? You should have the `resources` folder there

**Comment by linclt** [comment]
> Can you share the file/folder structure in your go project ? You should have the `resources` folder there

yes,it`s here 
![image](https://user-images.githubusercontent.com/46485507/140491692-10d42e72-3b3d-44af-b985-c7c5f71b052e.png)

**Comment by asticode** [comment]
This is really weird 🤔 

Can you share the ouput logs when you run the `bundler` ?

**Comment by linclt** [comment]
> This is really weird 🤔
> 
> Can you share the ouput logs when you run the `bundler` ?

C:\Users\Administrator\go\src\github.com\asticode\go-astilectron-demo>astilectron-bundler
2021/11/05 09:52:30 Bundling for environment windows/amd64
2021/11/05 09:52:30 Binding data
2021/11/05 09:52:30 Removing C:\Users\ADMINI~1\AppData\Local\Temp\2\astibundler\bind
2021/11/05 09:52:30 Creating C:\Users\ADMINI~1\AppData\Local\Temp\2\astibundler\bind
2021/11/05 09:52:30 Creating C:\Users\ADMINI~1\AppData\Local\Temp\2\astibundler\bind\vendor_astilectron_bundler
2021/11/05 09:52:30 Creating C:\Users\ADMINI~1\AppData\Local\Temp\2\astibundler\cache
2021/11/05 09:52:30 C:\Users\ADMINI~1\AppData\Local\Temp\2\astibundler\cache\astilectron-0.49.0.zip already exists, skipping download of https://github.com/asticode/astilectron/archive/v0.49.0.zip
2021/11/05 09:52:30 Copying C:\Users\ADMINI~1\AppData\Local\Temp\2\astibundler\cache\astilectron-0.49.0.zip to C:\Users\ADMINI~1\AppData\Local\Temp\2\astibundler\bind\vendor_astilectron_bundler\astilectron.zip
2021/11/05 09:52:30 C:\Users\ADMINI~1\AppData\Local\Temp\2\astibundler\cache\electron-windows-amd64-11.4.3.zip already exists, skipping download of https://github.com/electron/electron/releases/download/v11.4.3/electron-v11.4.3-win32-x64.zip
2021/11/05 09:52:30 Copying C:\Users\ADMINI~1\AppData\Local\Temp\2\astibundler\cache\electron-windows-amd64-11.4.3.zip to C:\Users\ADMINI~1\AppData\Local\Temp\2\astibundler\bind\vendor_astilectron_bundler\electron.zip
2021/11/05 09:52:30 Creating C:\Users\ADMINI~1\AppData\Local\Temp\2\astibundler\bind\resources
2021/11/05 09:52:30 Copying C:\Users\Administrator\go\src\github.com\asticode\go-astilectron-demo\resources to C:\Users\ADMINI~1\AppData\Local\Temp\2\astibundler\bind\resources
2021/11/05 09:52:30 Generating C:\Users\Administrator\go\src\github.com\asticode\go-astilectron-demo\bind_windows_amd64.go
2021/11/05 09:52:35 Running rsrc for icon C:\Users\Administrator\go\src\github.com\asticode\go-astilectron-demo\resources\icon.ico into C:\Users\Administrator\go\src\github.com\asticode\go-astilectron-demo\windows.syso
2021/11/05 09:52:35 Removing C:\Users\Administrator\go\src\github.com\asticode\go-astilectron-demo\output\windows-amd64
2021/11/05 09:52:35 Creating C:\Users\Administrator\go\src\github.com\asticode\go-astilectron-demo\output\windows-amd64
2021/11/05 09:52:35 Building for os windows and arch amd64 astilectron: 0.49.0 electron: 11.4.3
2021/11/05 09:52:35 Executing go build -ldflags -H "windowsgui" -X "main.AppName=test" -X "main.BuiltAt=2021-11-05 09:52:35.0766983 +0000 GMT m=+4.792497401" -X "main.VersionAstilectron=0.49.0" -X "main.VersionElectron=11.4.3" -o C:\Users\Administrator\go\src\github.com\asticode\go-astilectron-demo\output\windows-amd64\binary github.com\asticode\go-astilectron-demo
2021/11/05 09:52:50 Moving C:\Users\Administrator\go\src\github.com\asticode\go-astilectron-demo\output\windows-amd64\binary to C:\Users\Administrator\go\src\github.com\asticode\go-astilectron-demo\output\windows-amd64\test.exe

C:\Users\Administrator\go\src\github.com\asticode\go-astilectron-demo>

**Comment by linclt** [comment]
> This is really weird 🤔
> 
> Can you share the ouput logs when you run the `bundler` ?

![image](https://user-images.githubusercontent.com/46485507/140492330-9bdd9140-41c1-406d-8bc3-7d6aff791a4d.png)

**Comment by linclt** [comment]
> This is really weird 🤔
> 
> Can you share the ouput logs when you run the `bundler` ?

![image](https://user-images.githubusercontent.com/46485507/140492456-b81757a9-66d9-4dbe-9721-25f846a9f81b.png)

**Comment by linclt** [comment]
> This is really weird 🤔
> 
> Can you share the ouput logs when you run the `bundler` ?
![image](https://user-images.githubusercontent.com/46485507/140492560-18278f0c-aa41-45d9-94b0-19a70469b9a9.png)

**Comment by asticode** [comment]
Can you share logs when you run the generated binary in a Windows terminal ?

**Comment by linclt** [comment]
> Can you share logs when you run the generated binary in a Windows terminal ?

![image](https://user-images.githubusercontent.com/46485507/140493046-fbc497a6-ad32-498c-b3d3-d3f20efde7fd.png)

**Comment by asticode** [comment]
Sorry, I meant logs when you run `test.exe` in a terminal

**Comment by linclt** [comment]
> Sorry, I meant logs when you run `test.exe` in a terminal

sorry, i am not sure that i understand your meaning, do you mean this:
![image](https://user-images.githubusercontent.com/46485507/140493901-d86a1e98-30d9-4619-9f00-e81980fc6a6f.png)

**Comment by linclt** [comment]
> Sorry, I meant logs when you run `test.exe` in a terminal

it just start and looks like this:
![image](https://user-images.githubusercontent.com/46485507/140494020-8e6ec1e1-b103-4514-a693-a639b734565e.png)

**Comment by asticode** [comment]
Could you replace

```go
// Create logger
l := log.New(log.Writer(), log.Prefix(), log.Flags())
```

with

```go
// Create logger
f, err := os.Open("/your/path/log.txt")
if err != nil {
  log.Fatal(err)
}
defer f.Close()
l := log.New(f, log.Prefix(), log.Flags())
```

Make sure to replace `"/your/path/log.txt"` with a valid path for a new log file.

Run `test.exe` again and share the content of this new log file.

**Comment by linclt** [comment]
> Could you replace
> 
> ```go
> // Create logger
> l := log.New(log.Writer(), log.Prefix(), log.Flags())
> ```
> 
> with
> 
> ```go
> // Create logger
> f, err := os.Open("/your/path/log.txt")
> if err != nil {
>   log.Fatal(err)
> }
> defer f.Close()
> l := log.New(f, log.Prefix(), log.Flags())
> ```
> 
> Make sure to replace `"/your/path/log.txt"` with a valid path for a new log file.
> 
> Run `test.exe` again and share the content of this new log file.

ok

**Comment by linclt** [comment]
> Could you replace
> 
> ```go
> // Create logger
> l := log.New(log.Writer(), log.Prefix(), log.Flags())
> ```
> 
> with
> 
> ```go
> // Create logger
> f, err := os.Open("/your/path/log.txt")
> if err != nil {
>   log.Fatal(err)
> }
> defer f.Close()
> l := log.New(f, log.Prefix(), log.Flags())
> ```
> 
> Make sure to replace `"/your/path/log.txt"` with a valid path for a new log file.
> 
> Run `test.exe` again and share the content of this new log file.

package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"time"

	"github.com/asticode/go-astikit"
	"github.com/asticode/go-astilectron"
	bootstrap "github.com/asticode/go-astilectron-bootstrap"
	"github.com/asticode/go-astilectron-demo/goend/cache"
	"github.com/asticode/go-astilectron-demo/goend/regedit"
	"github.com/asticode/go-astilectron-demo/parameters"
)

// Constants
const htmlAbout = `Welcome on <b>Astilectron</b> demo!<br>
This is using the bootstrap and the bundler.`

// Vars injected via ldflags by bundler
var (
	AppName            string
	BuiltAt            string
	VersionAstilectron string
	VersionElectron    string
)

// Application Vars
var (
	fs    = flag.NewFlagSet(os.Args[0], flag.ContinueOnError)
	debug = fs.Bool("d", false, "enables the debug mode")
	W     *astilectron.Window
	h     *Handler
	R     *regedit.Regedit
)

func main() {
	// 初始化全局变量

	// 初始化message handler
	handler := new(Handler)
	handler.Parameters = parameters.New()

	// 初始化cache
	cache.InitGoCache()
	cache.GoCache.Set("cacheStatus", "cache is ready", 24*time.Hour)

	// 初始化配置注册表
	R = regedit.New("`SOFTWARE\\NeMatRepair`").Init()

	// Create logger
	// Create logger
	f, err := os.Open("C:/Users/Administrator/Desktop/log.txt")
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()
	l := log.New(f, log.Prefix(), log.Flags())

	// Create logger
	// l := log.New(log.Writer(), log.Prefix(), log.Flags())
	// Parse flags
	fs.Parse(os.Args[1:])

	// Run bootstrap
	l.Printf("Running app built at %s\n", BuiltAt)
	if err := bootstrap.Run(bootstrap.Options{
		AstilectronOptions: astilectron.Options{
			AppName:            AppName,
			AppIconDarwinPath:  "resources/bitbug_favicon.icns",
			AppIconDefaultPath: "resources/bitbug_favicon.ico",
			SingleInstance:     true, //true只能启动一个，false能启动多个
			VersionAstilectron: VersionAstilectron,
			VersionElectron:    VersionElectron,
		},
		Debug:  *debug,
		Logger: l,
		OnWait: func(app *astilectron.Astilectron, ws []*astilectron.Window, _ *astilectron.Menu, _ *astilectron.Tray, _ *astilectron.Menu) error {

			W = ws[0]
			W.OpenDevTools()

			// SendMessage("goToJs", "go send to js", func(m *bootstrap.MessageIn) {

			// 	// Unmarshal
			// 	var s string
			// 	if err := json.Unmarshal(m.Payload, &s); err != nil {
			// 		return
			// 	}

			// 	// Process message
			// 	log.Printf("received %s\n", s)

			// 	SendMessage("goToJs", s, func(m *bootstrap.MessageIn) {

			// 		// Unmarshal
			// 		var s string
			// 		if err := json.Unmarshal(m.Payload, &s); err != nil {
			// 			return
			// 		}

			// 		// Process message
			// 		log.Printf("received %s\n", s)
			// 	})

			// })

			return nil
		},
		Windows: []*bootstrap.Window{{
			Homepage:       "index.html",
			MessageHandler: handler.handleMessages,
			Options: &astilectron.WindowOptions{
				Width:           astikit.IntPtr(780),
				Height:          astikit.IntPtr(850),
				MinWidth:        astikit.IntPtr(780),
				MinHeight:       astikit.IntPtr(850),
				BackgroundColor: astikit.StrPtr("#0d0e13"),
				UseContentSize:  astikit.BoolPtr(true),
				Center:          astikit.BoolPtr(true),
				Frame:           astikit.BoolPtr(false), //取消标题栏
				WebPreferences: &astilectron.WebPreferences{
					DevTools:           astikit.BoolPtr(true),
					EnableRemoteModule: astikit.BoolPtr(true),
					WebviewTag:         astikit.BoolPtr(true),
					WebSecurity:        astikit.BoolPtr(true),
				},
				// Icon: astikit.StrPtr("C:/Users/Administrator/go/src/github.com/asticode/go-astilectron-demo/resources/icon.ico"),
			},
		}},
		// 任务栏右下角功能区出现了icon
		// TrayOptions: &astilectron.TrayOptions{
		// 	Image: astikit.StrPtr("C:/Users/Administrator/go/src/github.com/asticode/go-astilectron-demo/resources/icon.ico"),
		// },
	}); err != nil {
		l.Fatal(fmt.Errorf("running bootstrap failed: %w", err))

	}
}

do i do it in the right way?

**Comment by linclt** [comment]
> > Could you replace
> > ```go
> > // Create logger
> > l := log.New(log.Writer(), log.Prefix(), log.Flags())
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > with
> > ```go
> > // Create logger
> > f, err := os.Open("/your/path/log.txt")
> > if err != nil {
> >   log.Fatal(err)
> > }
> > defer f.Close()
> > l := log.New(f, log.Prefix(), log.Flags())
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Make sure to replace `"/your/path/log.txt"` with a valid path for a new log file.
> > Run `test.exe` again and share the content of this new log file.
> 
> package main
> 
> import ( "flag" "fmt" "log" "os" "time"
> 
> ```
> "github.com/asticode/go-astikit"
> "github.com/asticode/go-astilectron"
> bootstrap "github.com/asticode/go-astilectron-bootstrap"
> "github.com/asticode/go-astilectron-demo/goend/cache"
> "github.com/asticode/go-astilectron-demo/goend/regedit"
> "github.com/asticode/go-astilectron-demo/parameters"
> ```
> 
> )
> 
> // Constants const htmlAbout = `Welcome on <b>Astilectron</b> demo!<br> This is using the bootstrap and the bundler.`
> 
> // Vars injected via ldflags by bundler var ( AppName string BuiltAt string VersionAstilectron string VersionElectron string )
> 
> // Application Vars var ( fs = flag.NewFlagSet(os.Args[0], flag.ContinueOnError) debug = fs.Bool("d", false, "enables the debug mode") W *astilectron.Window h *Handler R *regedit.Regedit )
> 
> func main() { // 初始化全局变量
> 
> ```
> // 初始化message handler
> handler := new(Handler)
> handler.Parameters = parameters.New()
> 
> // 初始化cache
> cache.InitGoCache()
> cache.GoCache.Set("cacheStatus", "cache is ready", 24*time.Hour)
> 
> // 初始化配置注册表
> R = regedit.New("`SOFTWARE\\NeMatRepair`").Init()
> 
> // Create logger
> // Create logger
> f, err := os.Open("C:/Users/Administrator/Desktop/log.txt")
> if err != nil {
> 	log.Fatal(err)
> }
> defer f.Close()
> l := log.New(f, log.Prefix(), log.Flags())
> 
> // Create logger
> // l := log.New(log.Writer(), log.Prefix(), log.Flags())
> // Parse flags
> fs.Parse(os.Args[1:])
> 
> // Run bootstrap
> l.Printf("Running app built at %s\n", BuiltAt)
> if err := bootstrap.Run(bootstrap.Options{
> 	AstilectronOptions: astilectron.Options{
> 		AppName:            AppName,
> 		AppIconDarwinPath:  "resources/bitbug_favicon.icns",
> 		AppIconDefaultPath: "resources/bitbug_favicon.ico",
> 		SingleInstance:     true, //true只能启动一个，false能启动多个
> 		VersionAstilectron: VersionAstilectron,
> 		VersionElectron:    VersionElectron,
> 	},
> 	Debug:  *debug,
> 	Logger: l,
> 	OnWait: func(app *astilectron.Astilectron, ws []*astilectron.Window, _ *astilectron.Menu, _ *astilectron.Tray, _ *astilectron.Menu) error {
> 
> 		W = ws[0]
> 		W.OpenDevTools()
> 
> 		// SendMessage("goToJs", "go send to js", func(m *bootstrap.MessageIn) {
> 
> 		// 	// Unmarshal
> 		// 	var s string
> 		// 	if err := json.Unmarshal(m.Payload, &s); err != nil {
> 		// 		return
> 		// 	}
> 
> 		// 	// Process message
> 		// 	log.Printf("received %s\n", s)
> 
> 		// 	SendMessage("goToJs", s, func(m *bootstrap.MessageIn) {
> 
> 		// 		// Unmarshal
> 		// 		var s string
> 		// 		if err := json.Unmarshal(m.Payload, &s); err != nil {
> 		// 			return
> 		// 		}
> 
> 		// 		// Process message
> 		// 		log.Printf("received %s\n", s)
> 		// 	})
> 
> 		// })
> 
> 		return nil
> 	},
> 	Windows: []*bootstrap.Window{{
> 		Homepage:       "index.html",
> 		MessageHandler: handler.handleMessages,
> 		Options: &astilectron.WindowOptions{
> 			Width:           astikit.IntPtr(780),
> 			Height:          astikit.IntPtr(850),
> 			MinWidth:        astikit.IntPtr(780),
> 			MinHeight:       astikit.IntPtr(850),
> 			BackgroundColor: astikit.StrPtr("#0d0e13"),
> 			UseContentSize:  astikit.BoolPtr(true),
> 			Center:          astikit.BoolPtr(true),
> 			Frame:           astikit.BoolPtr(false), //取消标题栏
> 			WebPreferences: &astilectron.WebPreferences{
> 				DevTools:           astikit.BoolPtr(true),
> 				EnableRemoteModule: astikit.BoolPtr(true),
> 				WebviewTag:         astikit.BoolPtr(true),
> 				WebSecurity:        astikit.BoolPtr(true),
> 			},
> 			// Icon: astikit.StrPtr("C:/Users/Administrator/go/src/github.com/asticode/go-astilectron-demo/resources/icon.ico"),
> 		},
> 	}},
> 	// 任务栏右下角功能区出现了icon
> 	// TrayOptions: &astilectron.TrayOptions{
> 	// 	Image: astikit.StrPtr("C:/Users/Administrator/go/src/github.com/asticode/go-astilectron-demo/resources/icon.ico"),
> 	// },
> }); err != nil {
> 	l.Fatal(fmt.Errorf("running bootstrap failed: %w", err))
> 
> }
> ```
> 
> }
> 
> do i do it in the right way?

i run test.exe and log.txt is empty,but still get this:
![image](https://user-images.githubusercontent.com/46485507/140497096-d5958d2d-c94e-4ceb-968d-21f65ffcae97.png)

**Comment by asticode** [comment]
Can you replace `*debug` with `true`?

**Comment by linclt** [comment]
> Can you replace `*debug` with `true`?

i replace it with true, but still get the same result

**Comment by asticode** [comment]
`log.txt` is still empty?

**Comment by linclt** [comment]
> `log.txt` is still empty?

yes

**Comment by asticode** [comment]
Did you manage to solve your problem ?

**Comment by linclt** [comment]
> Did you manage to solve your problem ?

Finally, I found the reason, it `is because of Asset:    Asset,AssetDir: AssetDir, I delete them
