### ISSUE TITLE
Running the bundled app

### ISSUE THREAD

**Issue by carlskii** [asticode/go-astilectron-demo#8]
Hi, 

I just bundled the demo app which created `Astilectron demo.app` folder on my Mac. How do I now run the app?

**Comment by asticode** [comment]
@carlskii you can simply navigate with the `Finder` to the directory path of `Astilectron demo.app` and double click the icon :)

Did it work?

**Comment by carlskii** [comment]
No it just shows up as folder not an app. 

Carl

**Comment by asticode** [comment]
Hmm this is weird:

- on which MacOSX version are you on?
- can you tell me the full folder tree under the `Astilectron demo.app` folder?

**Comment by carlskii** [comment]
Apologies. It actually works. There were some strange things happening in my environment.
